In [1]:
import pandas as pd
test_df = pd.read_csv(r"E:\APU_Predictive_Maintenance\Artifacts\preprocessed\test_preprocessed\test_preprocessed.csv")
test_df.head()

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_15_trend,sensor_17_rolling_mean,sensor_17_rolling_std,sensor_17_trend,sensor_20_rolling_mean,sensor_20_rolling_std,sensor_20_trend,sensor_21_rolling_mean,sensor_21_rolling_std,sensor_21_trend
0,2,-1.57053,-1.627251,-1.845178,0.417725,1.734366,-0.020725,-0.013357,-0.46522,1.823473,...,-0.004952,0.188998,-0.840616,-0.004565,0.197959,-0.832405,0.002646,-1.470298,-0.830872,0.002677
1,2,-1.57053,-1.627251,-1.845178,0.417725,1.734366,-0.020725,-0.013357,-0.46522,1.823473,...,-0.004952,0.188998,-0.840616,-0.004565,0.197959,-0.832405,0.002646,-1.470298,-0.830872,0.002677
2,2,-1.57053,-1.627251,-1.845178,0.417725,1.734366,-0.020725,-0.013357,-0.46522,1.823473,...,-0.004952,0.188998,-0.840616,-0.004565,0.197959,-0.832405,0.002646,-1.470298,-0.830872,0.002677
3,2,-1.57053,-1.627251,-1.845178,0.417725,1.734366,-0.020725,-0.991147,-0.46522,1.823473,...,-0.004952,0.188998,-0.840616,-0.004565,0.197959,-0.832405,0.002646,-1.470298,-0.830872,0.002677
4,2,-1.57053,-1.627251,-1.845178,0.417725,1.734366,-0.020725,-0.013357,-0.46522,1.823473,...,-0.004952,0.188998,-0.840616,-0.004565,0.197959,-0.832405,0.002646,-1.470298,-0.830872,0.002677

In [2]:

train_df = pd.read_csv(r"E:\APU_Predictive_Maintenance\Artifacts\preprocessed\train_preprocessed\train_preprocessed.csv")
train_df.head()

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_15_trend,sensor_17_rolling_mean,sensor_17_rolling_std,sensor_17_trend,sensor_20_rolling_mean,sensor_20_rolling_std,sensor_20_trend,sensor_21_rolling_mean,sensor_21_rolling_std,sensor_21_trend
0,1,-1.57053,0.746493,0.864455,0.417725,-0.889706,-0.291006,-0.187969,0.537852,-0.706737,...,-0.004952,-0.053141,-0.840616,-0.004565,-0.908486,-0.832405,0.002646,-1.561555,-0.830872,0.002677
1,1,-1.57053,0.746493,0.864455,0.417725,-0.889706,-0.291006,-0.187969,0.537852,-0.706737,...,-0.004952,-0.053141,-0.840616,-0.004565,-0.908486,-0.832405,0.002646,-1.561555,-0.830872,0.002677
2,1,-1.57053,0.746493,0.864455,0.417725,-0.889706,-0.291006,-0.187969,0.537852,-0.706737,...,-0.004952,-0.053141,-0.840616,-0.004565,-0.908486,-0.832405,0.002646,-1.561555,-0.830872,0.002677
3,1,-1.57053,0.746493,0.864455,0.417725,-0.889706,-0.291006,2.064381,0.537852,-0.706737,...,-0.004952,-0.053141,-0.840616,-0.004565,-0.908486,-0.832405,0.002646,-1.561555,-0.830872,0.002677
4,1,-1.57053,0.746493,0.864455,0.417725,-0.889706,-0.291006,-0.187969,0.537852,-0.706737,...,-0.004952,-0.053141,-0.840616,-0.004565,-0.908486,-0.832405,0.002646,-1.561555,-0.830872,0.002677

In [3]:
train_df.columns

Index(['engine_id', 'cycle', 'op_setting_1', 'op_setting_2', 'op_setting_3',
       'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6',
       'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11',
       'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16',
       'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21',
       'anomaly_score', 'fault_label', 'fault_type', 'fault_target', 'RUL',
       'cycle_normalized', 'sensor_2_rolling_mean', 'sensor_2_rolling_std',
       'sensor_2_trend', 'sensor_3_rolling_mean', 'sensor_3_rolling_std',
       'sensor_3_trend', 'sensor_4_rolling_mean', 'sensor_4_rolling_std',
       'sensor_4_trend', 'sensor_7_rolling_mean', 'sensor_7_rolling_std',
       'sensor_7_trend', 'sensor_8_rolling_mean', 'sensor_8_rolling_std',
       'sensor_8_trend', 'sensor_9_rolling_mean', 'sensor_9_rolling_std',
       'sensor_9_trend', 'sensor_11_rolling_mean', 'sensor_11_rolling_std',
       'sensor_11_trend', 'sensor_12_rolling_mean', 'sensor_12_rolling_std',
       'sensor_12_trend', 'sensor_13_rolling_mean', 'sensor_13_rolling_std',
       'sensor_13_trend', 'sensor_14_rolling_mean', 'sensor_14_rolling_std',
       'sensor_14_trend', 'sensor_15_rolling_mean', 'sensor_15_rolling_std',
       'sensor_15_trend', 'sensor_17_rolling_mean', 'sensor_17_rolling_std',
       'sensor_17_trend', 'sensor_20_rolling_mean', 'sensor_20_rolling_std',
       'sensor_20_trend', 'sensor_21_rolling_mean', 'sensor_21_rolling_std',
       'sensor_21_trend'],
      dtype='object')

In [7]:
test_df.columns

Index(['engine_id', 'cycle', 'op_setting_1', 'op_setting_2', 'op_setting_3',
       'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6',
       'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11',
       'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16',
       'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21',
       'anomaly_score', 'fault_label', 'fault_type', 'fault_target', 'RUL',
       'cycle_normalized', 'sensor_2_rolling_mean', 'sensor_2_rolling_std',
       'sensor_2_trend', 'sensor_3_rolling_mean', 'sensor_3_rolling_std',
       'sensor_3_trend', 'sensor_4_rolling_mean', 'sensor_4_rolling_std',
       'sensor_4_trend', 'sensor_7_rolling_mean', 'sensor_7_rolling_std',
       'sensor_7_trend', 'sensor_8_rolling_mean', 'sensor_8_rolling_std',
       'sensor_8_trend', 'sensor_9_rolling_mean', 'sensor_9_rolling_std',
       'sensor_9_trend', 'sensor_11_rolling_mean', 'sensor_11_rolling_std',
       'sensor_11_trend', 'sensor_12_rolling_mean', 'sensor_12_rolling_std',
       'sensor_12_trend', 'sensor_13_rolling_mean', 'sensor_13_rolling_std',
       'sensor_13_trend', 'sensor_14_rolling_mean', 'sensor_14_rolling_std',
       'sensor_14_trend', 'sensor_15_rolling_mean', 'sensor_15_rolling_std',
       'sensor_15_trend', 'sensor_17_rolling_mean', 'sensor_17_rolling_std',
       'sensor_17_trend', 'sensor_20_rolling_mean', 'sensor_20_rolling_std',
       'sensor_20_trend', 'sensor_21_rolling_mean', 'sensor_21_rolling_std',
       'sensor_21_trend'],
      dtype='object')

In [8]:
len(test_df.columns)

74

In [9]:
len(train_df.columns)

74